version: "2"
services:
  db:
    image: postgres
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  service:
    image: tomcat
    links:
      - db
    volumes:
      - ./backend/target/todo:/usr/local/tomcat/webapps/todo
    ports:
      - '8080:8080'
  redis_master:
    image: redis
    container_name: redis
  redis_slave_1:
    image: redis
    command: redis-server --slaveof redis_master 6379
    links:
      - redis_master
  redis_slave_2:
    image: redis
    command: redis-server --slaveof redis_master 6379
    links:
      - redis_master
